version: '3.8'

services:
  agrotech-web:
    build: .
    container_name: agrotech_app
    ports:
      - "8501:8501"
    environment:
      - MANDI_API_KEY=${MANDI_API_KEY}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
